version: 2
jobs:
  build:
    working_directory: /circle-ci-example
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
            pip install \
              docker-compose==1.12.0
      - run:
          name: Build application Docker image
          command: |
            docker-compose build
      - run:
          name: Log in to docker hub
          command: |
            docker login --username=${DOCKER_HUB_USERNAME} --password=${DOCKER_HUB_TOKEN}
      - run:
          name: Tag docker images
          command: |
            docker tag circleciexample_test-service-one:latest frast/circle-ci-example-test-service-one
            docker tag circleciexample_test-service-two:latest frast/circle-ci-example-test-service-two
      - run:
          name: Push docker images
          command: |
            docker push frast/circle-ci-example-test-service-one
            docker push frast/circle-ci-example-test-service-two